ansible_network_os: cisco.nxos.nxos
# ansible_connection: ansible.netcommon.network_cli
ansible_connection: ansible.netcommon.httpapi
ansible_user: admin
ansible_password: '{{ lookup("env", "ANSIBLE_NETWORK_SSH_PASS") }}'
# ansible_network_cli_type: libssh
