all:
  vars:
    ansible_ssh_common_args: "_o StrictHostKeyChecking=no"
  hosts:
    dc1-spine1:
      ansible_host: "172.21.203.11"
    dc1-spine2:
      ansible_host: "172.21.203.12"
    dc1-leaf1:
      ansible_host: "172.21.203.13"
    dc1-leaf2:
      ansible_host: "172.21.203.14"
    dc1-bgw1:
      ansible_host: "172.21.203.16"
    dc1-bgw2:
      ansible_host: "172.21.203.17"
    dc2-spine1:
      ansible_host: "172.21.203.18"
    dc2-spine2:
      ansible_host: "172.21.203.19"
    dc2-leaf1:
      ansible_host: "172.21.203.20"
    dc2-leaf2:
      ansible_host: "172.21.203.21"
    dc2-bgw1:
      ansible_host: "172.21.203.22"
    dc2-bgw2:
      ansible_host: "172.21.203.23"
  children:
    dc1_spines:
      hosts:
        dc1-spine1:
        dc1-spine2:
    dc1_leafs:
      hosts:
        dc1-leaf1:
        dc1-leaf2:
    dc1_bgws:
      hosts:
        dc1-bgw1:
        dc1-bgw2:
    dc1_nxos:
      children:
        dc1-spines:
        dc1-leafs:
        dc1-bgws:
    dc1:
      children:
        dc1_spines:
        dc1_leafs:
        dc1_bgws:
    dc2_spines:
      hosts:
        dc2-spine1:
        dc2-spine2:
    dc2_leafs:
      hosts:
        dc2-leaf1:
        dc2-leaf2:
    dc2_bgws:
      hosts:
        dc2-bgw1:
        dc2-bgw2:
    dc2_nxos:
      children:
        dc2_spines:
        dc2_leafs:
        dc2_bgws:
    dc2:
      children:
        dc2_spines:
        dc2_leafs:
        dc2_bgws:
    spines:
      children:
        dc1_spines:
        dc2_spines:
    leafs:
      children:
        dc1_leafs:
        dc2_leafs:
    bgws:
      children:
        dc1_bgws:
        dc2_bgws:
    all_nxos:
      children:
        dc1_spines:
        dc1_leafs:
        dc1_bgws:
        dc2_spines:
        dc2_leafs:
        dc2_bgws:
    all_network:
      children:
        all_nxos:
