---
- name: Create users
  cisco.nxos.nxos_user:
    name: "{{ item.username }}"
    configured_password: "{{ item.password }}"
    sshkey: "{{ item.sshkey | default(omit) }}"
    role: "{{ item.role }}"
    state: present
    update_password: on_create
  loop: "{{ users }}"
  when: users is defined
