---
- name: Create users
  cisco.nxos.nxos_user:
    name: "{{ item.username }}"
    configured_password: "{{ item.password }}"
    role: "{{ item.role }}"
    state: present
    update_password: on_create
  loop: "{{ users }}"

- name: Configure global evpn Parameters
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true
