---
- name: Create users
  cisco.nxos.nxos_user:
    name: "{{ item.username }}"
    configured_password: "{{ item.password }}"
    role: "{{ item.role }}"
    state: present
    update_password: on_create
  loop: "{{ users }}"

- name: Configure global evpn Parameters
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true

- name: Save the running configuration
  cisco.nxos.nxos_config:
    save_when: modified

- name: Backup NXOS Configs
  cisco.nxos.nxos_config:
    backup: false
    backup_options:
      filename: "{{ inventory_hostname }}-config.cisco"
      dir_path: config_backups
