---
# tasks file for spines
#
- name: Enable Features
  cisco.nxos.nxos_feature:
    feature: "{{ item.feature }}"
    state: enabled
  loop: "{{ spines_features }}"

- name: Configure loopback interfaces
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface }}"
        enabled: true
  loop: "{{ loopbacks }}"
  when: loopbacks is defined

- name: Configure loopbacks IP Addresses
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.interface }}"
        ipv4:
          - address: "{{ item.addr }}/{{ item.mask }}"
  loop: "{{ loopbacks }}"
  when: loopbacks is defined

- name: Configure Ethernet Interfaces
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface }}"
        enabled: true
  loop: "{{ ethernet_l3_interfaces }}"
  when: ethernet_l3_interfaces is defined

- name: Configure L3 ethernet interfaces
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.interface }}"
        redirects: "{{ item.redirects }}"
  loop: "{{ ethernet_l3_interfaces }}"
  when: ethernet_l3_interfaces is defined

- name: Configure IP unnumbered
  cisco.nxos.nxos_config:
    lines:
      - medium p2p
      - no ip redirects
      - ip unnumbered loopback0
    parents:
      - "interface {{ item.interface }}"
  loop: "{{ ethernet_l3_interfaces }}"
  when: ethernet_l3_interfaces is defined

- name: Save the running configuration
  cisco.nxos.nxos_config:
    save_when: modified
