# File: spines/tasks/system.yml
---
- name: Enable Features
  cisco.nxos.nxos_feature:
    feature: "{{ item.feature }}"
    state: "{{ item.state | default('enabled') }}"
  loop: "{{ spines_features }}"
  when: spines_features is defined

- name: Configure SNMP Server
  cisco.nxos.nxos_snmp_server:
    config:
      communities: "{{ spines_snmp.communities | default(omit) }}"
      location: "{{ snmp.location }}"
      contact: "{{ snmp.contact }}"
      hosts: "{{ spine_snmp_hosts | default(omit) }}"
    state: "{{ item.state | default('merged') }}"
  when: spines_snmp is defined
