# File: spines/tasks/system.yml
---
- name: Configure System Settings
  cisco.nxos.nxos_system:
    config:
      hostname: "{{ item.hostname | default(inventory_hostname) }}"
      domain_lookup: "{{ item.domain_lookup | default(omit) }}"
      domain_name: "{{ item.domain_name | default(false) }}"
      name_servers: "{{ item.name_servers | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ spines_system }}"
  when: spines_system is defined

- name: Enable Features
  cisco.nxos.nxos_feature:
    feature: "{{ item.feature }}"
    state: "{{ item.state | default('enabled') }}"
  loop: "{{ spines_features }}"
  when: spines_features is defined

- name: Configure SNMP Server
  cisco.nxos.nxos_snmp_server:
    config:
      communities: "{{ spines_snmp.communities | default(omit) }}"
      location: "{{ snmp.location }}"
      contact: "{{ snmp.contact }}"
      hosts: "{{ spine_snmp_hosts | default(omit) }}"
    state: "{{ item.state | default('merged') }}"
  when: spines_snmp is defined
