# File: spines/tasks/system.yml
---
- name: Enable Features
  cisco.nxos.nxos_feature:
    feature: "{{ item.feature }}"
    state: "{{ item.state | default('enabled') }}"
  loop: "{{ spines_features }}"
  when: spines_features is defined

- name: Configure System Settings
  cisco.nxos.nxos_system:
    hostname: "{{ item.hostname | default(inventory_hostname) }}"
    system_mtu: "{{ item.system_mtu | default(default) }}"
    domain_lookup: "{{ item.domain_lookup | default(omit) }}"
    domain_name: "{{ item.domain_name | default(false) }}"
    name_servers: "{{ item.name_servers | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ spines_system }}"
  when: spines_system is defined

- name: Configure SNMP Server
  cisco.nxos.nxos_snmp_server:
    config:
      communities: "{{ spines_snmp.communities | default(omit) }}"
      location: "{{ snmp.location }}"
      contact: "{{ snmp.contact }}"
      hosts: "{{ spine_snmp_hosts | default(omit) }}"
    state: "{{ item.state | default('merged') }}"
  when: spines_snmp is defined

- name: Configure global PIM settings
  cisco.nxos.nxos_pim:
    ssm_range: "{{ item.ssm_range | default(omit) }}"
    bfd: "{{ item.bfd | default(omit) }}"
  loop: "{{ spines_pim }}"
  when: spines_pim is defined

- name: Configure rp-address for PIM
  cisco.nxos.nxos_pim_rp_address:
    rp_address: "{{ item.rp_address }}"
    group_list: "{{ item.group_list }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ spines_rp_address }}"
  when: spines_rp_address is defined

- name: Configure anycast-rp
  cisco.nxos.nxos_config:
    lines:
      - "ip pim anycast-rp {{ anycast_rp }} {{ router_id }}"
      - "ip pim anycast-rp {{ anycast_rp }} {{ router_id }}"
  when: anycast_rp and router_id is defined
