# Main playbook
#
- name: Configure Spines
  gather_facts: false
  hosts: spines
  roles:
    - role: spines
    - role: all

- name: Configure Leafs
  gather_facts: false
  hosts: leafs
  roles:
    - role: leafs
    - role: all
