# Main playbook
- name: Configure Spines
  gather_facts: false
  hosts: spines
  roles:
    - role: all_nxos
    - role: spines

- name: Configure Leafs
  gather_facts: false
  hosts: leafs
  roles:
    - role: all_nxos
    - role: leafs

- name: Configure BGWs
  gather_facts: false
  hosts: bgws
  roles:
    - role: all_nxos
    - role: bgws
