- name: Backup Configs
  gather_facts: false
  hosts: nxos
  tasks:
    - name: Backup DC1 NXOS Configs
      cisco.nxos.nxos_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}-config.cisco"
          dir_path: config_backups
