- name: Testing Cisco with Ansible
  gather_facts: false
  hosts: dc1_leafs
  tasks:
    - name: Show version
      cisco.nxos.nxos_command:
        commands: show version
      register: version

    - name: Write version to file per device
      copy:
        content: "{{ version.stdout[0] }}"
        dest: "tmp/{{ inventory_hostname }}_version.txt"

    - name: Show configuration
      cisco.nxos.nxos_command:
        commands: show running-config
      register: config

    - name: Write configuration to file per device
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "tmp/{{ inventory_hostname }}_config.txt"
